### ISSUE TITLE
add "OS" section at bottom, move os-type and build version there, add new row before build-version called "OS version" with $OS $Version - $Codename

### ISSUE THREAD

**Issue by star-buck** [ds9-extras/kcm-about-extended#1]
So section below Network looks like this:

OS

OS Type: 64bit
OS version: Maui 18 - Paria
Build version: 20160715.1324

**Comment by star-buck** [comment]
@shadeslayer : Can you fix this?

**Comment by shadeslayer** [comment]
Ack, working on it

**Comment by shadeslayer** [comment]
Fixed, shipped in snapshots from 20160721 and onwards
